<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>Shock12.Client</AssemblyName>
    <RootNamespace>Shock12.Client</RootNamespace>
    <Version>1.0.2</Version>
    <Authors>BensBurnedWaffles</Authors>
    <Company>BensBurnedWaffles</Company>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <Nullable>disable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <SptPath Condition="'$(SptPath)' == ''">C:\SPT4.1.2\SPT</SptPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>$(SptPath)\BepInEx\core\BepInEx.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="0Harmony"><HintPath>$(SptPath)\BepInEx\core\0Harmony.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>$(SptPath)\EscapeFromTarkov_Data\Managed\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine"><HintPath>$(SptPath)\EscapeFromTarkov_Data\Managed\UnityEngine.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(SptPath)\EscapeFromTarkov_Data\Managed\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
</Project>
