<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <AssemblyName>Shock12</AssemblyName>
    <Version>1.0.2</Version>
    <Authors>BensBurnedWaffles</Authors>
    <Company>BensBurnedWaffles</Company>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(Configuration)\Shock12\</OutputPath>
    <SptPath Condition="'$(SptPath)' == ''">C:\SPT4.1.2\SPT\SPT_Runtime</SptPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="SemanticVersioning">
      <HintPath>$(SptPath)\SemanticVersioning.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Common">
      <HintPath>$(SptPath)\SPTarkov.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.DI">
      <HintPath>$(SptPath)\SPTarkov.DI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="SPTarkov.Server.Core">
      <HintPath>$(SptPath)\SPTarkov.Server.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
